# Generated by Django 5.2.15 on 2026-07-07 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='deadline',
        ),
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
