# Generated by Django 5.2.15 on 2026-07-07 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_deadline_job_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
